---
sidebar: sidebar
permalink: task_cs_add_collector_ontap.html
keywords:  data collector, ONTAP
summary: Adding data collectors
---

= Configuring the NetApp ONTAP Data Collector

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Cloud Secure uses data collectors to collect file and user access data from devices. 


.Steps for Configuration 

. Log in as Administrator or Account Owner to your Cloud Secure environment. 
. Click *Admin > Data Collectors > +Data Collectors* 
+
The system displays the available Data Collectors.

. Click *+Monitor* in the NetApp ONTAP tile.
+ 
The system displays the Add Data Collector: ONTAP SVM configuration page. 

. Enter a unique name for the collector
. Select the agent that will be collecting the data 
. Enter the SVM management IP address
. Enter the user name to access the SVM
. Enter the password to access the SVM
. Click *+Add Collector*

.After you finish

* Click *Admin > Data Collectors* to check the status of the collector you configured.
+
There is normally a delay before the collector status is displayed.


